// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Core__Array = require("@rescript/core/src/Core__Array.res.js");

function test() {
  var arr = [
    1,
    2,
    3
  ];
  arr.push(4);
  var match = Core__Array.last(arr);
  if (match === 4) {
    console.log("mutable");
  } else {
    console.log("immutable");
  }
  var threes = Core__Array.make(3, "three");
  threes.forEach(function (prim) {
        console.log(prim);
      });
  var a = [
    1,
    2,
    3
  ];
  var b = [
    6,
    7,
    9
  ];
  var c = a.concat(b);
  var d = c.map(function (v) {
        return String(v) + ": " + "a".repeat(v);
      });
  console.log(d);
  console.log("Imperative insertion sort (featuring getUnsafe & setUnsafe):");
  var insertionSort = function (arr) {
    var n = arr.length;
    var j = 0;
    var key = 0;
    for(var i = 1; i < n; ++i){
      key = arr[i];
      j = i - 1 | 0;
      while(j >= 0 && arr[j] > key) {
        arr[j + 1 | 0] = arr[j];
        j = j - 1 | 0;
      };
      arr[j + 1 | 0] = key;
    }
  };
  var unsorted_arr = [
    9,
    2,
    1,
    6,
    3,
    1,
    0,
    6,
    5
  ];
  console.log(unsorted_arr);
  insertionSort(unsorted_arr);
  console.log(unsorted_arr);
  console.log("Quick sort using filters/concats");
  var quickSort = function (arr) {
    if (arr.length <= 1) {
      return arr;
    }
    var pivot = arr[arr.length / 2 | 0];
    var left = arr.filter(function (e) {
          return e < pivot;
        });
    var middle = arr.filter(function (e) {
          return e === pivot;
        });
    var right = arr.filter(function (e) {
          return e > pivot;
        });
    return quickSort(left).concat(quickSort(middle)).concat(quickSort(right));
  };
  var qs_arr = [
    6,
    1,
    4,
    2
  ];
  console.log(qs_arr);
  console.log(quickSort(qs_arr));
}

var name = "Arrays";

exports.name = name;
exports.test = test;
/* No side effect */
