// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Core__Array = require("@rescript/core/src/Core__Array.res.js");

function test() {
  var arr = [
    1,
    2,
    3
  ];
  arr.push(4);
  var match = Core__Array.last(arr);
  if (match === 4) {
    console.log("mutable");
  } else {
    console.log("immutable");
  }
  var threes = Core__Array.make(3, "three");
  threes.forEach(function (prim) {
        console.log(prim);
      });
  var a = [
    1,
    2,
    3
  ];
  var b = [
    6,
    7,
    9
  ];
  var c = a.concat(b);
  var d = c.map(function (v) {
        return String(v) + ": " + "a".repeat(v);
      });
  console.log(d);
}

var name = "Arrays";

exports.name = name;
exports.test = test;
/* No side effect */
