// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function test() {
  console.log("Hi from fn1 :)");
  console.log("Hello from fn" + (2).toString());
  console.log("Hello from fn" + (3).toString());
  var sum = (function (a, b) {
        return "Sum: " + String(a + b | 0);
      })(1, 3);
  console.log(sum);
  var fn4 = function (xOpt, y) {
    var x = xOpt !== undefined ? xOpt : "0";
    console.log("Coordinates: " + x + ", " + y);
  };
  fn4("1", "2");
  var fn5 = function (conf) {
    console.log("Booting up...");
    if (conf.length > 0) {
      console.log("Configuration:");
      conf.forEach(function (v) {
            console.log(v[0] + ": " + String(v[1]));
          });
      return ;
    }
    
  };
  fn5([
        [
          "barnaby",
          3
        ],
        [
          "wallaby",
          5
        ]
      ]);
  var drawCircle = function (length, radius) {
    if (radius !== undefined) {
      console.log("A cylinder of length " + length.toString() + " and diameter " + (radius << 1).toString());
    } else {
      console.log("A line of length " + length.toString());
    }
  };
  drawCircle(10, undefined);
  drawCircle(4, 1);
  drawCircle(22, undefined);
  var callFirst = function (count) {
    if (count > 0) {
      console.log("Hello " + count.toString());
      return callFirst(count - 1 | 0);
    }
    
  };
  callFirst(5);
}

var name = "Functions";

exports.name = name;
exports.test = test;
/* No side effect */
