// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function test() {
  console.log("hello!");
  console.log("Hello :)");
}

var name = "Let bindings";

exports.name = name;
exports.test = test;
/* No side effect */
