// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("rescript/lib/js/caml_obj.js");
var Core__List = require("@rescript/core/src/Core__List.res.js");
var Core__Option = require("@rescript/core/src/Core__Option.res.js");

function test() {
  var fst_lst = {
    hd: 1,
    tl: {
      hd: 2,
      tl: {
        hd: 3,
        tl: /* [] */0
      }
    }
  };
  console.log(fst_lst);
  var fmap = function (lst, f) {
    if (lst) {
      return Core__List.add(fmap(lst.tl, f), f(lst.hd));
    } else {
      return /* [] */0;
    }
  };
  var snd_lst = fmap(fst_lst, (function (i) {
          return "a".repeat(i);
        }));
  console.log(snd_lst);
  var mergeSort = function (lst) {
    var size = Core__List.length(lst);
    var helper = function (lst, len) {
      if (!lst) {
        return lst;
      }
      if (!lst.tl) {
        return lst;
      }
      var mid_point = len / 2 | 0;
      var match = Core__Option.getOr(Core__List.splitAt(lst, mid_point), [
            lst,
            /* [] */0
          ]);
      var sorted_left = helper(match[0], mid_point);
      var sorted_right = helper(match[1], len - mid_point | 0);
      var walk = function (l, r) {
        if (!r) {
          return l;
        }
        if (!l) {
          return r;
        }
        var rh = r.hd;
        var lh = l.hd;
        if (Caml_obj.lessequal(lh, rh)) {
          return Core__List.add(walk(l.tl, r), lh);
        } else {
          return Core__List.add(walk(l, r.tl), rh);
        }
      };
      return walk(sorted_left, sorted_right);
    };
    return helper(lst, size);
  };
  var unsorted_lst = {
    hd: 3,
    tl: {
      hd: 6,
      tl: {
        hd: 7,
        tl: {
          hd: 2,
          tl: {
            hd: 4,
            tl: {
              hd: 12,
              tl: {
                hd: 1,
                tl: /* [] */0
              }
            }
          }
        }
      }
    }
  };
  console.log(Core__List.toArray(unsorted_lst));
  console.log(Core__List.toArray(mergeSort(unsorted_lst)));
}

var name = "Lists";

exports.name = name;
exports.test = test;
/* No side effect */
