// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("rescript/lib/js/caml_obj.js");

function test() {
  var a = {
    name: "jonesy",
    job: "software developer",
    happy: true
  };
  if (!Caml_obj.equal(a, a)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "Records.res",
            48,
            4
          ],
          Error: new Error()
        };
  }
  var user = {
    username: "jar2333",
    displayname: "jar2333"
  };
  console.log(user);
  user.displayname = "Jose Ramos";
  console.log(user);
  var user2 = {
    username: "woofer",
    displayname: "Woofler Woofington",
    email: "woof@dog.net"
  };
  var newrecord = Caml_obj.obj_dup(user2);
  newrecord.email = "barker@gmail.com";
  var newrecord$1 = Caml_obj.obj_dup(user2);
  newrecord$1.email = "borker@hotmail.com";
  var newrecord$2 = Caml_obj.obj_dup(user2);
  newrecord$2.email = undefined;
  var check_email = function (u) {
    var e = u.email;
    if (e !== undefined) {
      console.log("email: " + e);
    } else {
      console.log("no email");
    }
  };
  check_email(user2);
  check_email(newrecord$2);
  var is_woofdog = function (u) {
    var match = u.email;
    if (match === "woof@dog.net") {
      return true;
    } else {
      return false;
    }
  };
  console.log(is_woofdog(user2));
  console.log(is_woofdog(newrecord$2));
  var has_email = function (u) {
    return u.email !== undefined;
  };
  console.log(has_email(user2));
  console.log(has_email(newrecord$2));
  var job_site_user = {
    name: "Jonathan Alouette Montserrat",
    job: "Senior Developer",
    happy: false,
    username: "jamo",
    displayname: "Jonesy Montserrat",
    email: "jamo@hotmail.com",
    resume_link: "https://storage.org/rhtrwe3rwrglknebjswejgjlrg"
  };
  var evaluate_fruit = function (v) {
    if (v.price > 5.0) {
      console.log("Too expensive!");
    } else {
      console.log("Cheap enough!");
    }
  };
  evaluate_fruit({
        color: "Red",
        price: 2.99
      });
  console.log(has_email(job_site_user));
}

var name = "Records";

exports.name = name;
exports.test = test;
/* No side effect */
