// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function pretty_print(t) {
  var helper = function (count, t) {
    var ind = "    ".repeat(count);
    var print_children = function (ch) {
      if (ch.length === 0) {
        return "[]";
      }
      var rest = ch.map(function (extra) {
              return helper(count + 1 | 0, extra);
            }).join(",\n" + ind);
      return "\r\n                    [\r\n                    " + ind + "    " + rest + "\r\n                    ]\r\n                    ";
    };
    return "\r\n        " + ind + "{\r\n        " + ind + "    val: " + t.val + "\r\n        " + ind + "    children: " + print_children(t.children) + "\r\n        " + ind + "}\r\n        ";
  };
  return helper(0, t);
}

function test() {
  console.log(10);
  console.log([
        1,
        2
      ]);
  var fmap = function (f, t) {
    return {
            val: f(t.val),
            children: t.children.map(function (extra) {
                  return fmap(f, extra);
                })
          };
  };
  var t_children = [
    {
      val: 1,
      children: []
    },
    {
      val: 2,
      children: [{
          val: 3,
          children: []
        }]
    }
  ];
  var t = {
    val: 0,
    children: t_children
  };
  var mapped_t = fmap((function (v) {
          return "a".repeat(v);
        }), t);
  console.log(mapped_t);
}

var name = "Types";

exports.name = name;
exports.pretty_print = pretty_print;
exports.test = test;
/* No side effect */
