// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function test() {
  console.log(10);
  console.log([
        1,
        2
      ]);
  var fmap = function (f, t) {
    return {
            val: f(t.val),
            children: t.children.map(function (extra) {
                  return fmap(f, extra);
                })
          };
  };
  var t_children = [
    {
      val: 1,
      children: []
    },
    {
      val: 2,
      children: [{
          val: 3,
          children: []
        }]
    }
  ];
  var t = {
    val: 0,
    children: t_children
  };
  var mapped_t = fmap((function (v) {
          return "a".repeat(v);
        }), t);
  console.log(mapped_t);
}

var name = "Types";

exports.name = name;
exports.test = test;
/* No side effect */
