// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Let = require("./scripts/Let.res.js");
var Lists = require("./scripts/Lists.res.js");
var Types = require("./scripts/Types.res.js");
var Arrays = require("./scripts/Arrays.res.js");
var Functions = require("./scripts/Functions.res.js");
var Exceptions = require("./scripts/Exceptions.res.js");

function MakeRunnable(M) {
  var run = function () {
    console.log("=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=");
    console.log("Running test: " + M.name);
    M.test();
    console.log("=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=");
  };
  return {
          run: run
        };
}

function run() {
  console.log("=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=");
  console.log("Running test: " + Let.name);
  Let.test();
  console.log("=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=");
}

var L = {
  run: run
};

run();

function run$1() {
  console.log("=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=");
  console.log("Running test: " + Types.name);
  Types.test();
  console.log("=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=");
}

var T = {
  run: run$1
};

run$1();

function run$2() {
  console.log("=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=");
  console.log("Running test: " + Arrays.name);
  Arrays.test();
  console.log("=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=");
}

var A = {
  run: run$2
};

run$2();

function run$3() {
  console.log("=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=");
  console.log("Running test: " + Lists.name);
  Lists.test();
  console.log("=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=");
}

var Li = {
  run: run$3
};

run$3();

function run$4() {
  console.log("=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=");
  console.log("Running test: " + Functions.name);
  Functions.test();
  console.log("=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=");
}

var Fs = {
  run: run$4
};

run$4();

function run$5() {
  console.log("=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=");
  console.log("Running test: " + Exceptions.name);
  Exceptions.test();
  console.log("=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=");
}

var Ex = {
  run: run$5
};

run$5();

exports.MakeRunnable = MakeRunnable;
exports.L = L;
exports.T = T;
exports.A = A;
exports.Li = Li;
exports.Fs = Fs;
exports.Ex = Ex;
/*  Not a pure module */
