// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Let = require("./scripts/Let.res.js");
var Types = require("./scripts/Types.res.js");
var Arrays = require("./scripts/Arrays.res.js");

function MakeRunnable(M) {
  var run = function () {
    console.log("=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=");
    console.log("Running test: " + M.name);
    M.test();
    console.log("=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=");
  };
  return {
          run: run
        };
}

function run() {
  console.log("=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=");
  console.log("Running test: " + Let.name);
  Let.test();
  console.log("=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=");
}

var L = {
  run: run
};

run();

function run$1() {
  console.log("=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=");
  console.log("Running test: " + Types.name);
  Types.test();
  console.log("=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=");
}

var T = {
  run: run$1
};

run$1();

function run$2() {
  console.log("=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=");
  console.log("Running test: " + Arrays.name);
  Arrays.test();
  console.log("=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=");
}

var A = {
  run: run$2
};

run$2();

exports.MakeRunnable = MakeRunnable;
exports.L = L;
exports.T = T;
exports.A = A;
/*  Not a pure module */
